/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package btl_jv;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Administrator
 */
public class QLTK_Jframe extends javax.swing.JFrame implements Serializable{
    
    /**
     * Creates new form QLTK_Jframe
     */
    int i = 0;
    public void fakeData(){
        KhachHang a1= new KhachHang("1", "Admin", "admin","Ha Noi","admin@gmail.com", 123456789, "admin", "admin", "user");
        KhachHang a2= new KhachHang("2", "User", "KTPM1","Ha Noi","user@gmail.com", 123456789, "user", "1234", "user");
        KhachHang a3= new KhachHang("3", "abc", "abc","Ha Noi","abc@gmail.com", 98653251, "abc", "1234", "user");
        dstk.add(a1);
        dstk.add(a2);
        dstk.add(a3);
    }
    public QLTK_Jframe() {
        initComponents();
        fakeData();
        loadtable(dstk);
    }
    int dongchon = -1;
    ArrayList<KhachHang> dstk = new ArrayList<KhachHang>();
    KhachHang tk = new KhachHang();
    DBEngine db = new DBEngine();
    String fName = "dsTaiKhoan.txt";
    public void loadtable(ArrayList<KhachHang> dstk) {
        tableTK.setModel(new TableTK(dstk));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        butthem = new javax.swing.JButton();
        butsua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttk = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtmk = new javax.swing.JTextField();
        txtten = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        butxoa = new javax.swing.JButton();
        txtemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttim = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        butghi = new javax.swing.JButton();
        butdoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        butthem.setText("Thêm");
        butthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butthemActionPerformed(evt);
            }
        });

        butsua.setText("Sửa");
        butsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butsuaActionPerformed(evt);
            }
        });

        jLabel7.setText("Mật khẩu:");

        jLabel5.setText("Email");

        butxoa.setText("Xoá");
        butxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butxoaActionPerformed(evt);
            }
        });

        jLabel1.setText("Phu trach:");

        jLabel6.setText("Tài khoản");

        jLabel2.setText("Họ tên");

        jLabel3.setText("Địa chỉ");

        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTK.setCellSelectionEnabled(true);
        tableTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTK);

        jLabel4.setText("Sđt");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("QUẢN LÝ TÀI KHOẢN");

        buttim.setText("Tìm kiếm");
        buttim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttimActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        butghi.setText("Ghi file");
        butghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butghiActionPerformed(evt);
            }
        });

        butdoc.setText("Đọc file");
        butdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butdocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtdiachi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsdt, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtemail))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtmk)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 39, Short.MAX_VALUE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butsua)
                    .addComponent(butxoa)
                    .addComponent(buttim)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(butghi)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(butthem, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(butdoc)))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txttk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtmk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(butdoc)
                        .addGap(18, 18, 18)
                        .addComponent(butghi)
                        .addGap(18, 18, 18)
                        .addComponent(butthem)
                        .addGap(18, 18, 18)
                        .addComponent(buttim)
                        .addGap(18, 18, 18)
                        .addComponent(butsua)
                        .addGap(18, 18, 18)
                        .addComponent(butxoa)))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butthemActionPerformed
        // TODO add your handling code here:
        try {
            String userName= getTxttk().getText();
            i = ++i;
        String hoTen = getTxtten().getText();
        String phuTrach = getTxtid().getText();
        String diaChi = getTxtdiachi().getText();
        String email = getTxtemail().getText();
        int sdt = Integer.parseInt(getTxtsdt().getText());
        String passWord = getTxtmk().getText();
        tk = new KhachHang(String.valueOf(i), hoTen, phuTrach, diaChi, email, sdt, userName, passWord, "user");
        int dem=0;
        for(KhachHang i:dstk){
            if(tk.userName.compareToIgnoreCase(i.userName)==0){
                if(dstk.contains(i)){
                    JOptionPane.showMessageDialog(this,"Tên tài khoản ko được trùng nhau");
                    dem++;
                }  
            }
        }
        if(dem==0){
            dstk.add(tk);
        }
        loadtable(dstk);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
        
    }//GEN-LAST:event_butthemActionPerformed

    private void butsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butsuaActionPerformed
        // TODO add your handling code here:
        dongchon = tableTK.getSelectedRow();
        if (dongchon != -1) {
        try {
            tk = dstk.get(dongchon);
            tk.setId(tk.id);
            tk.setHoten(getTxtten().getText() + "");
            tk.setDiachi(getTxtdiachi().getText() + "");
            tk.setEmail(getTxtemail().getText() + "");
            tk.setSdt(Integer.parseInt(getTxtsdt().getText()));
            tk.setPhutrach(getTxtid().getText()+"");
            tk.setUserName(getTxttk().getText()+"");
            tk.setPassWord(getTxtmk().getText()+"");
            dstk.set(dongchon, tk);
            JOptionPane.showMessageDialog(this, "Sua thanh cong","Thong bao",JOptionPane.WIDTH);
            loadtable(dstk);
        
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, e.toString());
        }
        }
        
    }//GEN-LAST:event_butsuaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn đóng ?", "Thong bao", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void butxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butxoaActionPerformed
        // TODO add your handling code here:
        int row= tableTK.getSelectedRow();
        if(row ==-1)
            JOptionPane.showMessageDialog(this, " vui long chon tai khoan can xoa","Thong bao",JOptionPane.ERROR_MESSAGE);
        else{
            int confirm =JOptionPane.showConfirmDialog(this,"Ban chac chan muon xoa ?","Xac nhan",JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                dstk.remove(row);
                loadtable(dstk);
            }
        }
    }//GEN-LAST:event_butxoaActionPerformed

    private void tableTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTKMouseClicked
        // TODO add your handling code here:
        dongchon = tableTK.getSelectedRow();
        if(dongchon != -1){
            tk = dstk.get(dongchon);
            txtten.setText(tk.hoten);
            txtid.setText(tk.phutrach);
            txtemail.setText(tk.email);
            txtdiachi.setText(tk.diachi);
            txtsdt.setText(String.valueOf(tk.sdt));
            txttk.setText(tk.userName);
            txtmk.setText(tk.passWord);
        }
    }//GEN-LAST:event_tableTKMouseClicked
    
    private void buttimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttimActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<KhachHang> tkh= new ArrayList<>();
            String tim= getTxtten().getText().trim();
            for(KhachHang i :dstk){
                if( tim.compareToIgnoreCase(i.hoten)==0){
                    if(!tkh.contains(i))
                        tkh.add(i);
                }
            }
            loadtable(tkh);
            if(tkh.isEmpty()){
                JOptionPane.showMessageDialog(null, "không tìm thấy");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tim kiem: " + e.toString());
        }
    }//GEN-LAST:event_buttimActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
            loadtable(dstk);
            txtid.setText("");
            txtten.setText("");
            txtsdt.setText("");
            txtemail.setText("");
            txttk.setText("");
            txtmk.setText("");
            txtdiachi.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void butghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butghiActionPerformed
        // TODO add your handling code here:
         try {
            db.luuFile(fName, dstk);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_butghiActionPerformed

    private void butdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butdocActionPerformed
        ArrayList<KhachHang> kh= null;
        try {
            kh = (ArrayList<KhachHang>) db.docFile(fName);
        } catch (Exception e) {
            System.out.println("Có lỗi: " + e.toString());
        } 
        loadtable(kh);
    }//GEN-LAST:event_butdocActionPerformed

    public JTextField getTxtid()throws Exception {
        if(txtid.getText().equals(""))
            throw new Exception("ko duoc de trong phu trach!");
        return txtid;
    }
    
    public JTextField getTxtdiachi() throws Exception{
        if(txtdiachi.getText().equals(""))
            throw new Exception("ko duoc de trong dia chi!");
        return txtdiachi;
    }

    public JTextField getTxtemail()throws Exception {
        if(txtemail.getText().equals(""))
            throw new Exception("ko duoc de trong email!");
        return txtemail;
    }

    public JTextField getTxtmk()throws Exception {
        if(txtmk.getText().equals(""))
            throw new Exception("ko duoc de trong mat khau!");
        return txtmk;
    }

    public JTextField getTxtsdt() throws Exception {
        if(txtsdt.getText().equals(""))
            throw new Exception("ko duoc de trong sdt!");
        return txtsdt;
    }

    public JTextField getTxtten() throws Exception{
        if(txtten.getText().equals(""))
            throw new Exception("ko duoc de trong ten!");
        return txtten;
    }

    public JTextField getTxttk() throws Exception{
        if(txttk.getText().equals(""))
            throw new Exception("ko duoc de trong userName!");
        return txttk;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLTK_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLTK_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLTK_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLTK_Jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLTK_Jframe().setVisible(true);
            }
        });
        System.gc();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butdoc;
    private javax.swing.JButton butghi;
    private javax.swing.JButton butsua;
    private javax.swing.JButton butthem;
    private javax.swing.JButton buttim;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton butxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTK;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmk;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtten;
    private javax.swing.JTextField txttk;
    // End of variables declaration//GEN-END:variables
}
