package btl_jv;

import btl_jv.QLPH;
import btl_jv.DBEngine;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class QuanLyPhanHoi extends javax.swing.JFrame {

    DBEngine db = new DBEngine();
    String fName = "dsPhanHoi.txt";
    ArrayList<QLPH> dsph = new ArrayList<>();
    int chon = -1;
    //File fileName = new File("PhanHoi_Excel.xlsx");

    public void luuFile() {
        try {
            db.luuFile(fName, dsph);
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    public void docFile() {
        try {
            dsph = (ArrayList) db.docFile(fName);
        } catch (Exception e) {
            System.out.println("Có lỗi: " + e.toString());
        }
    }

    public void loadtablePhanHoi() {
        tablePH.setModel(new TablePhanHoi(dsph));
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    public QuanLyPhanHoi() {
        initComponents();
        dsph.add(new QLPH("KH01", "Vũ Văn Thuấn", "anh1.jpg", "Tất cả các sản phẩm đều chất lượng, áo dày dặn màu sắc tươi sáng", 9.5));
        dsph.add(new QLPH("KH02", "Hoàng Thị Huệ", "anh2.png", "Sản phẩm đều chất lượng,có vài chiếc màu hơi khác so với còn lại", 8));
        dsph.add(new QLPH("KH03", "Trần Văn Cảnh", "anh4.jpg", "Thiếu 5 chiếc áo đồng phục màu hè", 5));
        dsph.add(new QLPH("KH04", "Nguyễn Thị Thu Hồng", "anh5.png", "Có 2 chiếc áo khoác đồng phục bị rách phần cánh tay", 6));
        dsph.add(new QLPH("KH05", "Trần Văn Hải", "anh10.png", "Tất cả các sản phẩm đều chất lượng, áo dày dặn màu sắc tươi sáng", 9));
        dsph.add(new QLPH("KH06", "Hoàng Hạnh Lan", "anh8.png", "Hẹn ngày 12 giao nhưng đến ngày 20 mới giao", 4.5));

        tablePH.setModel(new TablePhanHoi(dsph));
        ButtonGroup gr = new ButtonGroup();
        gr.add(radGiam);
        gr.add(radTang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radTang = new javax.swing.JRadioButton();
        radGiam = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePH = new javax.swing.JTable();
        btnTichCuc = new javax.swing.JButton();
        btnXayDung = new javax.swing.JButton();
        btnAn = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý phản hồi của khách hàng");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Quản lý phản hồi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Sắp xếp điểm");

        radTang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radTang.setText("Tăng dần");
        radTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radTang(evt);
            }
        });

        radGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radGiam.setText("Giảm dần");
        radGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radGiam(evt);
            }
        });

        tablePH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tablePH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePH);

        btnTichCuc.setBackground(new java.awt.Color(204, 204, 204));
        btnTichCuc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTichCuc.setText("Phản hồi tích cực");
        btnTichCuc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTichCuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTichCuc(evt);
            }
        });

        btnXayDung.setBackground(new java.awt.Color(204, 204, 204));
        btnXayDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXayDung.setText("Phản hồi xây dựng");
        btnXayDung.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnXayDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXayDung(evt);
            }
        });

        btnAn.setBackground(new java.awt.Color(204, 204, 204));
        btnAn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAn.setText("Ẩn phản hồi");
        btnAn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAn(evt);
            }
        });

        btnLuuFile.setBackground(new java.awt.Color(204, 204, 204));
        btnLuuFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuuFile.setText("Lưu file");
        btnLuuFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFile(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 204, 204));
        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(226, 226, 226))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnLuuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXayDung, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTichCuc, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radTang, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radTang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radGiam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTichCuc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnXayDung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnAn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLuuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void radTang(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTang
        Comparator<QLPH> c = new Comparator<QLPH>() {
            @Override
            public int compare(QLPH o1, QLPH o2) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                return Double.compare(o1.diemDG, o2.diemDG);
            }
        };
        Collections.sort(dsph, c);
        loadtablePhanHoi();
    }//GEN-LAST:event_radTang

    private void radGiam(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radGiam
        Comparator<QLPH> c = new Comparator<QLPH>() {
            @Override
            public int compare(QLPH o1, QLPH o2) {
                //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                return Double.compare(o2.diemDG, o1.diemDG);
            }
        };
        Collections.sort(dsph, c);
        loadtablePhanHoi();
    }//GEN-LAST:event_radGiam

    ArrayList<QLPH> dsPHXD = new ArrayList<>();
    private void btnXayDung(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXayDung
        for (QLPH s : dsph) {
            if (s.getDiemDG() <= 7) {
                dsPHXD.add(s);
                tablePH.setModel(new TablePhanHoi(dsPHXD));
            }
        }
    }//GEN-LAST:event_btnXayDung

    ArrayList<QLPH> dsPHTC = new ArrayList<>();
    private void btnTichCuc(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTichCuc
        for (QLPH s : dsph) {
            if (s.getDiemDG() > 7) {
                dsPHTC.add(s);
                tablePH.setModel(new TablePhanHoi(dsPHTC));
            }
        }
    }//GEN-LAST:event_btnTichCuc

    private void btnAn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAn
        try {
            int row = tablePH.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(QuanLyPhanHoi.this, "Chọn phản hồi muốn ẩn", "Lỗi", JOptionPane.ERROR_MESSAGE);
            } else {
                int confirm = JOptionPane.showConfirmDialog(QuanLyPhanHoi.this, "Bạn có chắc muốn ẩn phản hồi này?", "Xác nhận", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    dsph.remove(row);
                    loadtablePhanHoi();
                    JOptionPane.showMessageDialog(QuanLyPhanHoi.this, "Đã ẩn phản hồi", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.toString());
        }
    }//GEN-LAST:event_btnAn

    private void btnThoat(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat
        close();
    }//GEN-LAST:event_btnThoat

    private void btnLuuFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFile
        luuFile();
        JOptionPane.showMessageDialog(this,
                "Lưu file thành công !", "Thông báo", WIDTH);
    }//GEN-LAST:event_btnLuuFile

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        if (JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn đóng ?", "Thong bao", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyPhanHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyPhanHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAn;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTichCuc;
    private javax.swing.JButton btnXayDung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radGiam;
    private javax.swing.JRadioButton radTang;
    private javax.swing.JTable tablePH;
    // End of variables declaration//GEN-END:variables
}
